version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 27017:27017
    networks:
      - terryscord
  bot:
    image: ghcr.io/suiramdev/terryscord:main
    environment:
      - TOKEN=$TOKEN
      - MONGODB_URI=$MONGODB_URI
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - terryscord

networks:
  terryscord:
    driver: bridge